development: &defaults
  consumer_key: j1p6z904cukdsr8y
  consumer_secret: zkufiky9c3r27kvf
  consumer_handler: CreataryHandler
  site: https://local.telcoassetmarketplace.com:9443

test:
  <<: *defaults

production:
  <<: *defaults
