development: &defaults
  #site: https://local.telcoassetmarketplace.com:9443
  consumer_key: z7q3rgjzk18emh8t
  consumer_secret: d92wr0i8pfe1v8i2
  consumer_handler: TamHandler

test:
  <<: *defaults

production:
  <<: *defaults
